# Terralink SDI-12 on ESP32 (M5Stack Atom) - Coco Coir (Soilless) calibration
# Publishes clean Home Assistant entities:
#   - VWC (%)        -> "VWC"
#   - Temperature °C -> "Temperature"
#   - pwEC (dS/m)    -> "pwEC"
#
# Wiring (zero extra parts, as used here):
#   Terralink BLACK (GND)  -> Atom GND
#   Terralink RED   (+V)   -> Atom 5V (USB 5V)
#   Terralink WHITE (DATA) -> Atom GPIO26   [single-wire, TX-only in YAML]
#
# Notes:
# - SDI-12 is inverted, 1200 baud, 7-E-1, half-duplex.
# - We use ssieb's UART override to enable single-pin half-duplex.
# - Raw SP and bulk EC are kept "internal: true" to keep HA clean.
# - Address defaults to 1; change to 0 or 2..9 if needed.
#
# Tested with ESPHome 2025.9.x

esphome:
  name: terralink-coco-1

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# Keep logs relatively quiet in normal use.
logger:
  level: INFO
  # Uncomment for bus debugging:
  # level: DEBUG

api: {}   # Home Assistant native API (no encryption for simplicity)
ota:
  - platform: esphome
    password: "CHANGE_ME"  # optional, set your own

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Terralink-Setup"
    password: "12345678"

# Optional web UI for quick checks
web_server:
  port: 80
  local: true
  version: 2

# ---- External components for single-wire SDI-12 ----
external_components:
  - source: github://ssieb/esphome@uarthalf
    components: [ uart ]
    refresh: 1min
  - source: github://ssieb/esphome_components@sdi12
    components: [ sdi12 ]
    refresh: 1min

# ---- Single-pin UART on GPIO26 (inverted, half-duplex) ----
uart:
  - id: sdi12uart
    tx_pin:
      number: GPIO26
      inverted: true        # SDI-12 wire level is inverted
    baud_rate: 1200
    data_bits: 7
    parity: EVEN
    stop_bits: 1
    half_duplex: true       # single-wire: TX also serves as RX internally
    # Uncomment to see on-wire traffic in logs:
    # debug:
    #   direction: BOTH
    #   after:
    #     timeout: 20ms
    #   sequence:
    #     - lambda: UARTDebug::log_string(direction, bytes);

sdi12:
  - id: sdibus
    uart_id: sdi12uart

# ---- SDI-12 polling of the Terralink probe ----
sensor:
  # Internal helpers from D0 frame:
  - platform: sdi12
    address: 1                # try 0 or 2..9 if no response
    update_interval: 30s
    sensors:
      # Index mapping for Terralink D0: SP, EC, Temp
      - index: 1
        id: soil_permittivity  # SP (unitless)
        internal: true
        accuracy_decimals: 2
      - index: 2
        id: raw_ec_bulk       # bulk EC (dS/m)
        internal: true
        accuracy_decimals: 3   # keep more precision for math
        unit_of_measurement: "dS/m"
      - index: 3
        name: Temperature
        id: temperature_c
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        accuracy_decimals: 1

  # ---- VWC (%), calibrated for Coco Coir (Soilless) ----
  - platform: template
    name: VWC
    id: vwc_percent
    unit_of_measurement: "%"
    state_class: measurement
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    update_interval: 30s
    lambda: |-
      // Read SP from the SDI-12 frame
      float SP = id(soil_permittivity).state;
      if (isnan(SP) || SP <= 0) return NAN;

      // Soilless (Coco/Rockwool) polynomial
      const float Slope3 = 0.0000055728f;
      const float Slope2 = -0.000640228f;
      const float Slope1 = 0.0298804f;
      const float Intercept = 0.0214996f;

      float vwc = (Slope3*SP*SP*SP + Slope2*SP*SP + Slope1*SP + Intercept) * 100.0f;
      if (vwc < 0) vwc = 0;
      if (vwc > 100) vwc = 100;
      return vwc;
    filters:
      # Light smoothing without much lag (3 samples @ 30s = ~1.5 min span)
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1

  # ---- pwEC (dS/m) with temp compensation and Hilhorst multiplier ----
  - platform: template
    name: pwEC
    id: pore_ec
    unit_of_measurement: "dS/m"
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 30s
    lambda: |-
      float EC = id(raw_ec_bulk).state;   // bulk EC as reported (dS/m)
      float T  = id(temperature_c).state; // °C
      float SP = id(soil_permittivity).state;
      if (isnan(EC) || isnan(T) || isnan(SP)) return NAN;

      // Normalize bulk EC to 25°C (alpha ≈ 0.019 per °C)
      float bulk_25 = EC / (1.0f + 0.019f * (T - 25.0f));

      // Dielectric of pore water
      float eps_p = 80.3f - 0.37f * (T - 20.0f);

      // Hilhorst multiplier (soilless)
      const float hilhorstOffset = 6.0f;
      float denom = (SP - hilhorstOffset);
      if (fabsf(denom) < 0.25f) return NAN;   // avoid blow-up very close to offset

      float mult = eps_p / denom;

      // Clamp per vendor guidance
      if (mult > 20.0f) mult = 20.0f;
      if (mult < 0.0f)  mult = 20.0f;

      return bulk_25 * mult;
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1

# (Optional) quick device control:
# switch:
#   - platform: restart
#     name: "Restart Device"
